# docker compose --env-file .\.env up --build -d
services:
  database:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'PGPASSWORD=${DB_PASSWORD} pg_isready -h localhost -U ${DB_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s
  bunny-stream:
    build:
      context: .
      dockerfile: Dockerfile
    image: bunny-stream:1.0.0
    volumes:
      - type: bind
        source: .
        target: /app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      database:
        condition: service_healthy
